table 'Store Forecast'
	lineageTag: c3c48bfa-e310-4876-a988-9bb521c680ee

	column 'Week Ending'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: 543c5e45-c9fd-43d8-860f-4b5ca568eadb
		summarizeBy: none
		sourceColumn: Week Ending

	column 'Store ID'
		dataType: string
		isHidden
		lineageTag: b60bed54-ecb5-4dde-97f1-9c89d85f731a
		summarizeBy: none
		sourceColumn: Store ID

	column 'Forecast Pallets'
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: b33feebc-984a-4610-bfd4-cc207e85a00a
		sourceColumn: Forecast Pallets

	partition 'Store Forecast' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ProjectFolder & "outputs\store_forecast.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Selected = Table.SelectColumns(Promoted, {"week_ending", "store_id", "forecast_pallets"}),
				    Renamed = Table.RenameColumns(Selected, {{"week_ending", "Week Ending"}, {"store_id", "Store ID"}, {"forecast_pallets", "Forecast Pallets"}}),
				    Typed = Table.TransformColumnTypes(Renamed, {{"Week Ending", type date}, {"Store ID", type text}, {"Forecast Pallets", type number}}, "en-US")
				in
				    Typed

