table 'Store Weekly'
	lineageTag: 4278d5d5-66f5-48a3-b836-a5f38f84ff9a

	column 'Week Ending'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: 2ee149ec-37de-4072-b815-8b44a25e1c85
		summarizeBy: none
		sourceColumn: Week Ending

	column 'Store ID'
		dataType: string
		isHidden
		lineageTag: fec4fda1-c815-4b9f-a47c-ccde69bbd336
		summarizeBy: none
		sourceColumn: Store ID

	column 'Demand Pallets'
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: 98e2a2e2-eb6a-465f-b02b-d9a397f416f6
		sourceColumn: Demand Pallets

	column 'Delivered Pallets'
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: b9fc386b-9a74-4bd4-931a-7f2f437c96cd
		sourceColumn: Delivered Pallets

	column 'Backlog Pallets'
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: 087ac381-c593-4b15-ab67-5a4a849112c7
		sourceColumn: Backlog Pallets

	partition 'Store Weekly' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ProjectFolder & "data\store_weekly_history.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Selected = Table.SelectColumns(Promoted, {"week_ending", "store_id", "demand_pallets", "delivered_pallets", "backlog_pallets"}),
				    Renamed = Table.RenameColumns(Selected, {{"week_ending", "Week Ending"}, {"store_id", "Store ID"}, {"demand_pallets", "Demand Pallets"}, {"delivered_pallets", "Delivered Pallets"}, {"backlog_pallets", "Backlog Pallets"}}),
				    Typed = Table.TransformColumnTypes(Renamed, {{"Week Ending", type date}, {"Store ID", type text}, {"Demand Pallets", type number}, {"Delivered Pallets", type number}, {"Backlog Pallets", type number}}, "en-US")
				in
				    Typed

